export const ADD_PACKAGE = 'ADD_PACKAGE';
export const IS_CREATING_PACKAGE = 'IS_CREATING_PACKAGE';
export const IS_EDIT_PACKAGE_TITLE = 'IS_EDIT_PACKAGE_TITLE';
export const EDIT_PACKAGE_TITLE = 'EDIT_PACKAGE_TITLE';
