export const ADD_PACKAGE = 'ADD_PACKAGE';
export const IS_CREATING_PACKAGE = 'IS_CREATING_PACKAGE';
export const CHANGE_PACKAGE_TITLE = 'CHANGE_PACKAGE_TITLE';
export const CHANGE_PACKAGE_DESCRIPTION = 'CHANGE_PACKAGE_DESCRIPTION';
