export const ADD_PACKAGE = 'ADD_PACKAGE';
export const IS_CREATING_PACKAGE = 'IS_CREATING_PACKAGE';
export const CHANGE_PACKAGE_TITLE = 'CHANGE_PACKAGE_TITLE';
export const CHANGE_PACKAGE_DESCRIPTION = 'CHANGE_PACKAGE_DESCRIPTION';
export const CHANGE_FILTER_PACKAGE = 'CHANGE_FILTER_PACKAGE';
export const TOGGLE_ACTIVE_SEARCH = 'TOGGLE_ACTIVE_SEARCH';
export const CHANGE_PAGINATION_PACKAGE = 'CHANGE_PAGINATION_PACKAGE';
